apiVersion: v1
kind: Service
metadata:
  name: registry-admission
  namespace: registry-admission
  labels:
    name: registry-admission
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    name: registry-admission
