apiVersion: v1
kind: Service
metadata:
  name: registry-admission
  labels:
    name: registry-admission
spec:
  type: ClusterIP
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: registry-admission
