apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: registry-admission
  labels:
    name: registry-admission
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/registry-admission-certs"
webhooks:
  - name: registry-admission.tools.wmcloud.org
    clientConfig:
      service:
        name: registry-admission
        namespace: {{ .Release.Namespace }}
        path: "/"
      caBundle: ""
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    admissionReviewVersions: ["v1"]
    sideEffects: None
    namespaceSelector:
      matchExpressions:
        - key: name
          operator: NotIn
          values:
            # don't cause issues with kubernetes internals
            - "kube-system"
            # prevent chicken-and-egg problems with webhook certificates
            - "cert-manager"
            # so that the controller itself can start
            - "{{ .Release.Namespace }}"
