apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "registry-admission-webhook.name" . }}
  labels:
    {{- include "registry-admission-webhook.labels" . | nindent 4 }}
webhooks:
  - name: {{ .Values.webhookName }}
    clientConfig:
      service:
        name: {{ include "registry-admission-webhook.name" . }}
        namespace: {{ .Release.Namespace }}
        path: "/"
      caBundle: {{ .Values.caBundle }}
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]
    failurePolicy: Ignore
    admissionReviewVersions: ["v1"]
    sideEffects: None
    namespaceSelector:
      matchExpressions:
        - key: name
          operator: NotIn
          values:
            # don't cause issues with kubernetes internals
            - "kube-system"
            # so that the controller itself can start
            - "registry-admission"
