# Default values for registry-admission-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: docker-registry.tools.wmflabs.org/registry-admission
  # The following is for testing only
  # tag: latest
  # pullPolicy: Never
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: 50Mi
    cpu: 300m
  requests:
    memory: 50Mi
    cpu: 300m

webhook:
  failurePolicy: Fail

allowedRegistries: []
